### ISSUE TITLE
Panic on incorrect messages instead of controlled errors

### ISSUE THREAD

**Issue by SharliBeicon** [xoolive/rs1090#82]
Hello there!

When using the library I noticed that if you read an ASD-B message with crc != 0, the application panic instead of returning a controlled error. Allso happens when reading a DF number not supported. e.g:

```
thread 'tokio-runtime-worker' panicked at /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/rs1090-0.3.6/src/decode/mod.rs:305:60:
called `Result::unwrap()` on an `Err` value: Assertion("Invalid CRC in ADS-B message: 8010744")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```
thread 'tokio-runtime-worker' panicked at /app/libs/rs1090/crates/rs1090/src/decode/mod.rs:305:60:
called `Result::unwrap()` on an `Err` value: Parse("Could not match enum variant id = 3 on enum `DF`")
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I see that the issue is just right here:

https://github.com/xoolive/rs1090/blob/cf5584b5387ede3cf141bc1a077b5ee70bfed95f/crates/rs1090/src/decode/mod.rs#L305

The `unwrap` is making the application crash. Switching it with a `?` is enough since I already have tested it. If you want, I can send PR with the fix.

Thanks for your work, this library is so useful to me :)

**Comment by xoolive** [comment]
Thanks for the feedback. I am currently afk so a PR is very much welcome. Thank you

**Comment by SharliBeicon** [comment]
> Thanks for the feedback. I am currently afk so a PR is very much welcome. Thank you

https://github.com/xoolive/rs1090/pull/83 Done. 😄
